"""Add Department

Revision ID: 463177185d7e
Revises: c00b45b93f86
Create Date: 2024-07-10 04:16:46.147452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '463177185d7e'
down_revision = 'c00b45b93f86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('departments')
    # ### end Alembic commands ###
