"""rename department

Revision ID: 958e545d5842
Revises: 66ac16e0d171
Create Date: 2025-01-14 14:42:32.876289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '958e545d5842'
down_revision = '66ac16e0d171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###