"""rename address

Revision ID: b5c20f948a31
Revises: 463177185d7e
Create Date: 2024-07-10 12:22:02.202011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5c20f948a31'
down_revision = '463177185d7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column( 'departments', 'address', new_column_name= 'location' )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column( 'departments', 'location', new_column_name= 'address' )
    # ### end Alembic commands ###
